// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Serenify",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "Serenify",
            targets: ["AppModule"],
            bundleIdentifier: "me.Gutierrez.Elyan.Serenify",
            teamIdentifier: "52Q4M7N2WD",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .healthcareFitness
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "AppModule",
            resources: [
                .process("Resources/Sounds/forestSoundEffect.mp3"),
                .process("Resources/Sounds/oceanWavesSoundEffect.mp3"),
                .process("Resources/Sounds/whiteNoiseSoundEffect.mp3"),
                .process("Resources/Sounds/riverSoundEffect.mp3")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)
